#!/usr/bin/env python3
"""
generate_bandersnatch_conf.py
=============================
Turn an allowlist.txt (from resolve_deps.py) plus the target settings into a
bandersnatch.conf that mirrors ONLY the allowlisted packages/versions for the
chosen platforms and Python versions.

bandersnatch already produces a PEP 503 compliant /simple/ tree, per-file
SHA256 hashes, and (with json=true) the JSON metadata. We only need to point
it at the right allowlist and platform filters.
"""
from __future__ import annotations

import argparse

# Platforms to KEEP -> platforms to EXCLUDE in bandersnatch.
ALL_PLATFORMS = ["linux", "windows", "macos", "freebsd"]
# bandersnatch python filter tokens (py3.0 .. py3.14 supported by recent versions).
ALL_PY3 = [f"3.{m}" for m in range(0, 15)]


def py_excludes(keep_versions: list[str]) -> list[str]:
    keep_minor = {v if v.count(".") == 1 else ".".join(v.split(".")[:2]) for v in keep_versions}
    excl = ["py2"]  # drop all python 2
    for m in ALL_PY3:
        if m not in keep_minor:
            excl.append(f"py{m}")
    return excl


def platform_excludes(keep_platforms: list[str]) -> list[str]:
    return [p for p in ALL_PLATFORMS if p not in keep_platforms]


def build_conf(allowlist_lines, output_dir, master, workers, keep_json,
               keep_platforms, keep_pyversions, exclude_py_minor):
    platforms_block = platform_excludes(keep_platforms)
    if exclude_py_minor:
        platforms_block += py_excludes(keep_pyversions)

    packages = "\n    ".join(allowlist_lines)
    platforms = "\n    ".join(platforms_block)

    return f"""\
# Generated by generate_bandersnatch_conf.py -- do not edit by hand.
# Run bandersnatch on a CONNECTED machine, then copy `{output_dir}` to the
# disconnected host and serve it (see scripts/serve_mirror.sh).

[mirror]
directory = {output_dir}
master = {master}
json = {str(keep_json).lower()}
release-files = true
timeout = 30
global-timeout = 1800
workers = {workers}
hash-index = false
stop-on-error = false
storage-backend = filesystem
# Only fetch metadata for projects in the allowlist (huge speedup vs full sync).
diff-file = {output_dir}/mirrored-files

[plugins]
enabled =
    allowlist_project
    allowlist_release
    exclude_platform

[allowlist]
packages =
    {packages}

[blocklist]
# exclude_platform reads its platform/python tokens from here.
platforms =
    {platforms}
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--allowlist", default="allowlist.txt")
    ap.add_argument("--output-dir", default="./mirror")
    ap.add_argument("--master", default="https://pypi.org")
    ap.add_argument("--workers", type=int, default=4)
    ap.add_argument("--keep-json", dest="keep_json", action="store_true",
                    help="Mirror PyPI JSON metadata files (default).")
    ap.add_argument("--no-keep-json", dest="keep_json", action="store_false",
                    help="Do not mirror PyPI JSON metadata files.")
    ap.set_defaults(keep_json=True)
    ap.add_argument("--platforms", nargs="+", default=["linux", "windows"])
    ap.add_argument("--python-versions", nargs="+", default=["3.9", "3.10", "3.11", "3.12"])
    ap.add_argument("--no-exclude-python-minor", action="store_true",
                    help="Do not filter wheels by Python minor version (keeps all py3 wheels).")
    ap.add_argument("--out", default="bandersnatch.conf")
    args = ap.parse_args()

    with open(args.allowlist, encoding="utf-8") as f:
        lines = [ln.strip() for ln in f if ln.strip()]

    conf = build_conf(
        allowlist_lines=lines,
        output_dir=args.output_dir,
        master=args.master,
        workers=min(args.workers, 10),
        keep_json=args.keep_json,
        keep_platforms=args.platforms,
        keep_pyversions=args.python_versions,
        exclude_py_minor=not args.no_exclude_python_minor,
    )
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(conf)
    print(f"Wrote {args.out} ({len(lines)} allowlisted packages).")


if __name__ == "__main__":
    main()
